---
title: "Sample statistics as input data"
author: "Marcello Gallucci"
nickname: covsinput
topic: general
category: example
---


```{r echo=FALSE,results='hide'}
library(mcdocs)
mcdocs_init()

```


`r keywords("SEM, covariances, correlations, lavaan, SEMLj, jamovi")`

`r version("1.3.0")`


In this example, we demonstrate how to use a variances-covariances matrix as input data of `r modulename()`. We show input of `r modulename()` that is exactly the same for the _syntax sub-module_ and  _interactive sub-module_, the examples applyy to both modules. We focus more on the setup of the data, so the example would not be interpreted as for other cases.


# The data


For this example, we use the **Holzinger and Swineford dataset**, which is included in the [*lavaan* R package](https://lavaan.ugent.be). The dataset contains nine variables measured on 331 participants. While the original dataset provides disaggregated data, for the purposes of this example we treat the data as if only sample estimates — such as covariances or correlations — were available, similar to what one might find in published articles or statistical reports.

For the sake of comparison, here are the overall fit indices of a three-factor confirmatory factors analysis, with this structure

```
visual=~x1+x2+x3
textual=~x4+x5+x6
speed=~x7+x8+x9

```
`r tobecontinued`

`r include_examples()`
`r backto("gui","syntax")`
`r issues()`