---
title: "GUI SEM via lavaan in jamovi"
author: Marcello Gallucci
topic: gui
category: help
bibliography: 
     - bib.bib
link-citations: true

---


```{r echo=FALSE,results='hide'}
library(mcdocs)
mcdocs_init()
```

`r keywords("semlj,jamovi, lavaan, SEM")`

**SEMLj** GUI module based on lavaan 

`r version("1.3.*")` 


# Introduction


The `r modulename()` module is a `r jamovi` interface to `lavaan` R package [@lavaan]. The module offers a Graphical User Interface (point-and-click)  to build a model, which is translated in lavaan syntax and passed to R lavaan functions . All the available options are in the foldable panels below the variable definition fields. Thus, it is recommended that the user takes a look at `lavaan` [website](https://lavaan.ugent.be/index.html) for details.

# User Interface

When installed, the module sub-modules can be found in the `SEM` menu.

`r pic("pics/menu.png")`

Here we need `r opt("SEM (interactive)")`.

## Latent variables definition

`r pic("pics/gui/panel_vars.png")`

The  panel allows to define a set of endogenous and exogenous variables, measured by one or more observed variables. To make the interface simple and efficient This allows estimating almost all sort of structural equation models and path analysis (but check out the jamovi module [PATHj](https://pathj.github.io/), dedicated to path analysis). It allows for factor analysis models, but check out the jamovi CFA core command (in "Factor" menu) for a dedicated command.

Thus, the sub-module can estimate:

* Path analysis models
* Structural Equation models
* Multigroup Analysis
* Defined parameters (i.e a:=p1^2)

For each latent variable, the user defines the variable name (in the figure one changes _Endogenous 1_ into a name of a latent variable) and  specifies which observed variables (in the right field) are measures of the latent variable by bringing the observed variables into the right field. In the example portraited in the figure, _Endogenous 1_ is measured by $y5$,$y6$,$y7$ and $y8$, whereas the latent exogenous _ind_ is measured by $x1$,$x2$ and $x3$.

In this page, we assume that the user has named the endogenous latern variable _latent_dep_ and the exogenous latent variable _latent_ind_, as in the next figure.

`r pic("pics/gui/panel_vars2.png")`

One can define as many latent variables one needs by clicking on `r opt("Add New Latent")` button.


At the right bottom of the panel we find also the `r opt("Multigroup Analysis Factor")`, in which one puts the categorical variable defining groups for multi-group analyses.

## Type of variables

To obtain a standard SEM model, please be sure that the observed variables are marked as `continuous variable` in the dataset. You see a little _ruler_ icon on the left of the variable name, like this:

`r pic("pics/gui/input_type1.png")`

When variables are defined as `continuous`, they are considered continuous variables in `r modulename()`. 

Categorical variables can be analyzed if they are defined as dichotomous or ordinal variable. `r modulename()` treats variables as ordered variables if they are defined as `Nominal` or `Ordinal` in the dataset, like this:

`r pic("pics/gui/input_type2.png")`

When indicators are ordinal or nominal, Diagonal Weighted Least Squares is used for estimation, with robust standard error. Please refer to [lavaan documentation](https://lavaan.ugent.be/tutorial/cat.html) for more details.

## Second Order Factors

`r pic("pics/gui/input_gui_so1.png")`

This panel is useful to define second order factors, that is latent variables that are measured by other latent variables. See `r link_pages(nickname="secondorder")` for an example of usage.

## Endogenous models

`r pic("pics/gui/panel_endo.png")`

In this panel one specifies the relationship among latent variables (the stuctural relationships). The user can simply declare here what are the latent predictors of the latent endogenous variables. At least one relationship should be defined.

## Variances and covariances

`r pic("pics/gui/panel_variances.png")`

In this panel one specifies the variances and covariances to estimate (set free). Variances are specified by selecting twice a single variance (as for $y6$ in the figure). Covariances by selecting two variables and than click the central arrow.

## Custom model settings

`r pic("pics/gui/panel_custom.png")`

In this panel one specifies additional model settings, such as free variances or defined parameters by passing `lavaan` syntax, one directive per row. In the picture, for instance, the users frees the variance of $y7$ with the `y7~~y7` syntax, and define a new coefficient to estimate `a` as the square of the `p1` coefficient. The `pN` notation is the label of a coefficient that `r modulename()` automatically assigns to each estimated coefficient. To see what they are, simply select `r opt("Show parameters labels")` in the `r opt("Output options")` panel.

Syntax examples can be seen by selecting  `r opt("Show syntax examples")` in the `r opt("Output options")`, which returns in output the following table of examples:

`r pic("pics/gui/output_examples.png")`


## Model Options

`r pic("pics/syntax/panel_model.png")`

The `r opt("Estimation Method")` allows choosing the right estimation method available for a model. The `r opt("Automatic")` option (default) lets `lavaan` choose the right method depending to the type of model one is estimating.

`r pic("pics/syntax/panel_model2.png")`

`r opt("Constraints tests")` computes the $\chi^2$ test for contrainted coefficients (if any). In case one has more than one contraints, each constraint is tested uniquely (if `r opt("Univariate")` is flagged) and in addition to the previous ones (if `r opt("Cumulative")` is flagged).

Under `r opt("Data")` one can decide how to handle missing values.

The options for this panel are are:

`r panel_options("semljgui","panel_modeloptions")`


## Type of models

Users familiar with `lavaan` or with lavaan documentations may want to distinguish between different types of models, namely, `cfa` (confirmatory factor analysis), `sem` (structural equation models) and `growth` (individual growth models). These models enjoy the same underlying estimation procedure, but they are different in the options passed to `lavaan`. In `r modulename()`, one can obtain the same results as `sem` and `cfa` setup using the default options settings (unless you know you need some change). For `growth` model type, one needs to set `r opt("Intercepts->Observed variables")` to false (unselect it), and `r opt("Intercepts->Latent variables")` to true (select it) in the `r opt("Parameters Options")` panel, and you're a happy camper. 

## Model parameters 

`r pic("pics/syntax/panel_parameters.png")`

This panel offers many options to be passed to `lavaan` for specify parameters characteristics, such as how to compute their standard errors, their confidence intervals, or how to fix scales of latent variables.

In addition, it offers the `r opt("Indirect Effects")` option which computes and estimate all possible indirect effects (from exogenous to endogenous variables) present in the model.


The options are:

`r panel_options("semljgui","parameters_options")`

## Multi-group Analysis 

`r pic("pics/gui/panel_multigroup.png")`

Once a multi-group factor is set in the variable definition (see above), in this panel one can choose which parameters to fix as equal across groups.

The options are:

`r panel_options("semljgui","panel_multigroup")`


## Multilevel Analysis 

Multilevel models are not available in the GUI version of `r modulename()`. To estimate these models in `r jamovi`, please use `r link_pages(nickname="syntax_main")`

## Output Options

`r pic("pics/syntax/panel_output.png")`

This panel allows requesting all sort of additional information about the model results, such as the $R^2$'s, the implied and residual variances and covariances, and the modification indexes.

As regards predicted values, there are three possible types of predicted values that can be saved to the datasheet.

`r format_outputs("semljgui")`

The name of the new variables saved in the datasheet are indicated in a footnote of the `Info Table`.


The options are:

`r panel_options("semljgui","output_options")`



## Path Diagram

`r pic("pics/syntax/panel_diagram.png")`

This panel produces the path diagram graph  and allow for some change in shapes and orientation of the diagram. The digram is produced using R [semPlot module](http://sachaepskamp.com/semPlot), see also [@semplot]

The options are:

`r panel_options("semljgui","panel_pathdiagram")`



## Input Data

`r pic("pics/commons/panel_inputdata.png")`

This panel allows to use variances-covariances matrix as input data. Please see a detailed example here `r link_pages(nickname="covsinput")`.

`r panel_options("semljgui","panel_inputdata")`


`r include_examples()`

`r include_details()`

`r backto("help")`

`r issues()`


## References