---
title: "SEM via lavaan syntax in jamovi"
topic: syntax
category: help
nickname: syntax_main
output: 
  html_document:
     includes:
         in_header: ganalytics.txt
     toc: true
     toc_float:
        collapsed: false
bibliography: 
     - bib.bib
    
link-citations: true

---


```{r echo=FALSE,results='hide'}
source("../R/constants.R")
source("../R/functions.R")
```

`r keywords("semlj,jamovi, lavaan, SEM")`

**SEMLj** lavaan syntax module of the SEMLj suite for jamovi

`r version("0.3.*")` 
`r draft`


# Introduction

The `r modulename` module is a `r jamovi` interface to `lavaan` R package [@lavaan]. The module offers a syntax interface in which lavaan syntax for the model definition can be passed to the module. Almost everything you can pass in lavaan, you can pass it to `r modulename`. All the available options are in the foldable panels below the syntax field. Thus, it is recomended that the user takes a look at `lavaan` [website](https://lavaan.ugent.be/index.html) for details.

# User Interface

When installed, the module sub-modules can be found in the `SEM` menu.

`r pic("pics/menu.png")`

Here we need `r opt("SEM (syntax)")`.

## Syntax field

`r pic("pics/syntax/panel_syntax.png")`

The syntax pannel accepts `lavaan` syntax as decribed in [lavaan website](https://lavaan.ugent.be/tutorial/syntax1.html)
Whereas any syntax you submit will be passed to `lavaan::lavaan()`, `r modulename` may be not ready to understand the results and frame them in the output tables. At the moment, we have tested:

* Path analysis models
* Structural Equation models
* Confirmatory Factor Analysis
* Multigroup Analysis
* Multilevel Models
* Defined parameters (i.e a:=p1^2)
* free and fixing parameters via model syntax (i.e x~~x or a~0*1)

## Model Options

`r pic("pics/syntax/panel_model.png")`

The `r opt("Estimation Method")` allows choosing the right estimation method available for a model. The `r opt("Automatic")` option (default) lets `lavaan` choose the right method depending to the type of model one is estimating.

`r opt("Constraints tests")` computes the $\chi^2$ test for contrainted coefficients (if any). In case one has more than one contraints, each constraint is tested uniquely (if `r opt("Univariate")` is flagged) and in addition to the previous ones (if `r opt("Cumulative")` is flagged).

## Model parameters 

`r pic("pics/syntax/panel_parameters.png")`

This panel offers many options to be passed to `lavaan` for specify parameters charateristics, such as how to compute their standard errors, their confidence intervals, or how to fix scales of latent variables.

In addition, it offers the `r opt("Indirect Effects")` option which computes and estimate all possible indirect effects (from exogenous to endogenous variables) present in the model.

## Multi-group Analysis 

`r pic("pics/syntax/panel_multigroup.png")`

This panel allows for specifying a categorical variable (factor) defining groups of multi-group analysis. One simply writes the name of the factor variable in the `r opt("Factor for multi-group analysis")` field.

Once a multi-group analysis is set, one can choose which parameter to fix as equal across groups.

## Multilevel Analysis 

`r pic("pics/syntax/panel_multilevel.png")`

This panel allows specifying a categorical variable (factor) defining cluster variable of multgroup analysis. One simply writes the name of the factor variable in the `r opt("Factor for multi-group analysis")` field.

Once a cluster is set, the right syntax for specifying the multilevel model should be set in the syntax panel. See deailts [here](https://lavaan.ugent.be/tutorial/multilevel.html).

## Output Options

`r pic("pics/syntax/panel_output.png")`

This panel allows requesting all sort of additional information about the model results, such as the $R^2$'s, the implied and residual variances and covariances, and the modification indexes.

## Path Diagram

`r pic("pics/syntax/panel_diagram.png")`

This panel produces the path diagram graph  and allow for some change in shapes and orientation of the diagram. The digram is produced using R [semPlot module](http://sachaepskamp.com/semPlot), see also [@semplot]

# Examples

Some worked out examples of the analyses carried out with jamovi `r modulename` are posted here (more to come)

`r include_examples()`

# Details

Some more information about the module specs can be found here

`r include_details("pathj")`


`r issues()`


## References